name: Posts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update readme.md with latest blog posts.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in Jekyll posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://lucianofedericopereira.github.io/articles/feed.xml"
          template: $newline<tr><td>$date</td><td align="left"><a href='$url'>$title</a></td></tr>
          date_format: 'UTC: yyyy-mm'
