name: Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-stats:
    name: Update readme.md with account stats.
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/stats.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used          
          plugin_languages_recent_days: 90
          commits_authoring: Luciano Pereira, lucianofedericopereira, lucianofedericopereira@users.noreply.github.com
          extras_css: |
            h1.field { color: #25d366!important }
            h2.field, h3.field { color: #969289!important }
            .field svg { fill:#969289!important}
            footer {display: none!important}
          token: ${{ secrets.METRICS_TOKEN }}
